/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AActivityIdIndexRouteImport } from './routes/a/$activityId/index'
import { Route as AActivityIdPhoneRouteImport } from './routes/a/$activityId/phone'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AActivityIdIndexRoute = AActivityIdIndexRouteImport.update({
  id: '/a/$activityId/',
  path: '/a/$activityId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AActivityIdPhoneRoute = AActivityIdPhoneRouteImport.update({
  id: '/a/$activityId/phone',
  path: '/a/$activityId/phone',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a/$activityId/phone': typeof AActivityIdPhoneRoute
  '/a/$activityId/': typeof AActivityIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a/$activityId/phone': typeof AActivityIdPhoneRoute
  '/a/$activityId': typeof AActivityIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a/$activityId/phone': typeof AActivityIdPhoneRoute
  '/a/$activityId/': typeof AActivityIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/a/$activityId/phone' | '/a/$activityId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/a/$activityId/phone' | '/a/$activityId'
  id: '__root__' | '/' | '/a/$activityId/phone' | '/a/$activityId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AActivityIdPhoneRoute: typeof AActivityIdPhoneRoute
  AActivityIdIndexRoute: typeof AActivityIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$activityId/': {
      id: '/a/$activityId/'
      path: '/a/$activityId'
      fullPath: '/a/$activityId/'
      preLoaderRoute: typeof AActivityIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$activityId/phone': {
      id: '/a/$activityId/phone'
      path: '/a/$activityId/phone'
      fullPath: '/a/$activityId/phone'
      preLoaderRoute: typeof AActivityIdPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AActivityIdPhoneRoute: AActivityIdPhoneRoute,
  AActivityIdIndexRoute: AActivityIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
