/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AShareTokenIndexRouteImport } from './routes/a/$shareToken/index'
import { Route as AShareTokenPhoneRouteImport } from './routes/a/$shareToken/phone'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AShareTokenIndexRoute = AShareTokenIndexRouteImport.update({
  id: '/a/$shareToken/',
  path: '/a/$shareToken/',
  getParentRoute: () => rootRouteImport,
} as any)
const AShareTokenPhoneRoute = AShareTokenPhoneRouteImport.update({
  id: '/a/$shareToken/phone',
  path: '/a/$shareToken/phone',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a/$shareToken/phone': typeof AShareTokenPhoneRoute
  '/a/$shareToken/': typeof AShareTokenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a/$shareToken/phone': typeof AShareTokenPhoneRoute
  '/a/$shareToken': typeof AShareTokenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a/$shareToken/phone': typeof AShareTokenPhoneRoute
  '/a/$shareToken/': typeof AShareTokenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/a/$shareToken/phone' | '/a/$shareToken/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/a/$shareToken/phone' | '/a/$shareToken'
  id: '__root__' | '/' | '/a/$shareToken/phone' | '/a/$shareToken/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AShareTokenPhoneRoute: typeof AShareTokenPhoneRoute
  AShareTokenIndexRoute: typeof AShareTokenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$shareToken/': {
      id: '/a/$shareToken/'
      path: '/a/$shareToken'
      fullPath: '/a/$shareToken/'
      preLoaderRoute: typeof AShareTokenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$shareToken/phone': {
      id: '/a/$shareToken/phone'
      path: '/a/$shareToken/phone'
      fullPath: '/a/$shareToken/phone'
      preLoaderRoute: typeof AShareTokenPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AShareTokenPhoneRoute: AShareTokenPhoneRoute,
  AShareTokenIndexRoute: AShareTokenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
