CREATE TABLE "activity_segment" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "activity_segment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"activity_id" bigint NOT NULL,
	"agenda_line_id" bigint NOT NULL,
	"name" text NOT NULL,
	"segment_type" text NOT NULL,
	"start_time" timestamp with time zone NOT NULL,
	"end_time" timestamp with time zone NOT NULL,
	"location_text" text,
	"description" text,
	"owner_name" text,
	"status" text DEFAULT 'active' NOT NULL,
	"member_enabled" boolean DEFAULT false NOT NULL,
	"seating_enabled" boolean DEFAULT false NOT NULL,
	"created_by" text,
	"updated_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "uk_segment_id_activity" UNIQUE("id","activity_id"),
	CONSTRAINT "chk_segment_time_range" CHECK ("activity_segment"."start_time" <= "activity_segment"."end_time")
);
--> statement-breakpoint
CREATE TABLE "activity_segment_revision" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "activity_segment_revision_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"segment_id" bigint NOT NULL,
	"action" text NOT NULL,
	"snapshot" jsonb NOT NULL,
	"changed_by" text,
	"changed_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "activity_agenda_line" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "activity_agenda_line_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"activity_id" bigint NOT NULL,
	"line_type" text NOT NULL,
	"name" text,
	"sort_order" bigint DEFAULT 0 NOT NULL,
	"created_by" text,
	"updated_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "uk_agenda_line_id_activity" UNIQUE("id","activity_id")
);
--> statement-breakpoint
CREATE TABLE "account" (
	"id" text PRIMARY KEY NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"user_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp,
	"refresh_token_expires_at" timestamp,
	"scope" text,
	"password" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "session" (
	"id" text PRIMARY KEY NOT NULL,
	"expires_at" timestamp NOT NULL,
	"token" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"user_id" text NOT NULL,
	CONSTRAINT "session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean DEFAULT false NOT NULL,
	"image" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "file_asset" (
	"id" uuid PRIMARY KEY NOT NULL,
	"storage_key" text NOT NULL,
	"original_name" text NOT NULL,
	"mime_type" text NOT NULL,
	"size_bytes" bigint NOT NULL,
	"sha256" text NOT NULL,
	"status" text DEFAULT 'uploading' NOT NULL,
	"created_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "file_asset_storage_key_unique" UNIQUE("storage_key")
);
--> statement-breakpoint
CREATE TABLE "invitation_batch" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "invitation_batch_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"batch_no" text NOT NULL,
	"activity_id" bigint NOT NULL,
	"recipient_type" text DEFAULT 'member' NOT NULL,
	"template_id" bigint NOT NULL,
	"template_file_id" uuid NOT NULL,
	"template_name" text NOT NULL,
	"variables" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"issue_date" date NOT NULL,
	"created_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "invitation_batch_batch_no_unique" UNIQUE("batch_no"),
	CONSTRAINT "ck_invitation_batch_recipient_type" CHECK ("invitation_batch"."recipient_type" in ('member', 'organization'))
);
--> statement-breakpoint
CREATE TABLE "invitation_download_log" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "invitation_download_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"activity_id" bigint NOT NULL,
	"scope" text NOT NULL,
	"batch_id" bigint,
	"member_id" bigint,
	"organization_id" bigint,
	"file_count" integer NOT NULL,
	"result" text NOT NULL,
	"fail_reason" text,
	"downloaded_by" text,
	"downloaded_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "invitation_record" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "invitation_record_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"recipient_type" text DEFAULT 'member' NOT NULL,
	"activity_id" bigint NOT NULL,
	"member_id" bigint,
	"organization_id" bigint,
	"batch_id" bigint NOT NULL,
	"recipient_name" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "uk_invitation_record_member" UNIQUE("batch_id","member_id"),
	CONSTRAINT "uk_invitation_record_organization" UNIQUE("batch_id","organization_id"),
	CONSTRAINT "ck_invitation_record_recipient_target" CHECK ((
        ("invitation_record"."recipient_type" = 'member' and "invitation_record"."member_id" is not null and "invitation_record"."organization_id" is null)
        or
        ("invitation_record"."recipient_type" = 'organization' and "invitation_record"."member_id" is null and "invitation_record"."organization_id" is not null)
      ))
);
--> statement-breakpoint
CREATE TABLE "invitation_template" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "invitation_template_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"applicable_desc" text,
	"status" text DEFAULT 'enabled' NOT NULL,
	"template_file_id" uuid NOT NULL,
	"variables" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"created_by" text,
	"updated_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "activity_member" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "activity_member_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"activity_id" bigint NOT NULL,
	"project_id" bigint NOT NULL,
	"project_member_id" bigint NOT NULL,
	"member_id" bigint NOT NULL,
	"organization_id" bigint,
	"source" text,
	"group_name" text,
	"owner_name" text,
	"origin_type" text DEFAULT 'manual' NOT NULL,
	"remark" text,
	"created_by" text,
	"updated_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "uk_activity_member" UNIQUE("activity_id","member_id"),
	CONSTRAINT "uk_activity_member_id_activity_member" UNIQUE("id","activity_id","member_id")
);
--> statement-breakpoint
CREATE TABLE "member" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "member_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"gender" text,
	"company_position" text,
	"organization_id" bigint,
	"country_region_code" text,
	"country_region" text,
	"native_province_code" text,
	"native_province" text,
	"native_city_code" text,
	"native_city" text,
	"id_type" text,
	"id_number" text,
	"mobile" text,
	"phone" text,
	"email" text,
	"language" text,
	"remark" text,
	"merged_into_id" bigint,
	"status" text DEFAULT 'enabled' NOT NULL,
	"created_by" text,
	"updated_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "project_member" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "project_member_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"project_id" bigint NOT NULL,
	"member_id" bigint NOT NULL,
	"organization_id" bigint,
	"source_type" text DEFAULT 'manual' NOT NULL,
	"remark" text,
	"created_by" text,
	"updated_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "uk_project_member" UNIQUE("project_id","member_id"),
	CONSTRAINT "uk_project_member_id_project_member" UNIQUE("id","project_id","member_id")
);
--> statement-breakpoint
CREATE TABLE "segment_member" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "segment_member_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"segment_id" bigint NOT NULL,
	"activity_id" bigint NOT NULL,
	"activity_member_id" bigint NOT NULL,
	"member_id" bigint NOT NULL,
	"organization_id" bigint,
	"segment_role" text,
	"source" text,
	"group_name" text,
	"owner_name" text,
	"origin_type" text DEFAULT 'manual' NOT NULL,
	"remark" text,
	"created_by" text,
	"updated_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "uk_segment_member" UNIQUE("segment_id","activity_member_id"),
	CONSTRAINT "uk_segment_member_id_segment" UNIQUE("id","segment_id")
);
--> statement-breakpoint
CREATE TABLE "organization" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "organization_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"remark" text,
	"created_by" text,
	"updated_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "uk_organization_name" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "activity" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "activity_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"project_id" bigint NOT NULL,
	"activity_type" text NOT NULL,
	"name" text NOT NULL,
	"location" text,
	"start_time" timestamp with time zone NOT NULL,
	"end_time" timestamp with time zone NOT NULL,
	"total_budget" numeric(14, 2),
	"host_org" text,
	"organizer_org" text,
	"support_org" text,
	"guiding_org" text,
	"description" text,
	"publish_status" text DEFAULT 'draft' NOT NULL,
	"display_enabled" boolean DEFAULT false NOT NULL,
	"registration_enabled" boolean DEFAULT false NOT NULL,
	"created_by" text,
	"updated_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "uk_activity_id_project" UNIQUE("id","project_id"),
	CONSTRAINT "chk_activity_time_range" CHECK ("activity"."start_time" < "activity"."end_time")
);
--> statement-breakpoint
CREATE TABLE "activity_media" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "activity_media_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"activity_id" bigint NOT NULL,
	"file_id" uuid NOT NULL,
	"media_type" text NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "project" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "project_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"location" text,
	"start_time" timestamp with time zone,
	"end_time" timestamp with time zone,
	"total_budget" numeric(14, 2),
	"host_org" text,
	"organizer_org" text,
	"support_org" text,
	"guiding_org" text,
	"description" text,
	"publish_status" text DEFAULT 'draft' NOT NULL,
	"created_by" text,
	"updated_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "activity_resource" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "activity_resource_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"activity_id" bigint NOT NULL,
	"resource_type" text NOT NULL,
	"transport_scene" text,
	"name" text NOT NULL,
	"quantity" integer,
	"start_time" timestamp with time zone,
	"end_time" timestamp with time zone,
	"location" text,
	"vehicle_info" text,
	"driver_name" text,
	"driver_phone" text,
	"owner_name" text,
	"remark" text,
	"status" text DEFAULT 'active' NOT NULL,
	"created_by" text,
	"updated_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "uk_resource_id_activity" UNIQUE("id","activity_id"),
	CONSTRAINT "chk_resource_transport_only" CHECK ("activity_resource"."resource_type" = 'transport' OR ("activity_resource"."transport_scene" IS NULL AND "activity_resource"."vehicle_info" IS NULL AND "activity_resource"."driver_name" IS NULL AND "activity_resource"."driver_phone" IS NULL)),
	CONSTRAINT "chk_resource_time_range" CHECK ("activity_resource"."start_time" IS NULL OR "activity_resource"."end_time" IS NULL OR "activity_resource"."start_time" <= "activity_resource"."end_time")
);
--> statement-breakpoint
CREATE TABLE "resource_demand_link" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "resource_demand_link_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"activity_id" bigint NOT NULL,
	"demand_id" bigint NOT NULL,
	"resource_id" bigint NOT NULL,
	"created_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "uk_link_demand_resource" UNIQUE("demand_id","resource_id")
);
--> statement-breakpoint
CREATE TABLE "resource_member_binding" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "resource_member_binding_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"activity_id" bigint NOT NULL,
	"resource_id" bigint NOT NULL,
	"activity_member_id" bigint NOT NULL,
	"member_id" bigint NOT NULL,
	"remark" text,
	"created_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "uk_binding_resource_member" UNIQUE("resource_id","activity_member_id")
);
--> statement-breakpoint
CREATE TABLE "segment_resource_demand" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "segment_resource_demand_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"activity_id" bigint NOT NULL,
	"segment_id" bigint NOT NULL,
	"resource_type" text NOT NULL,
	"handling" text NOT NULL,
	"description" text,
	"estimated_count" integer,
	"owner_name" text,
	"created_by" text,
	"updated_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "uk_demand_segment_type" UNIQUE("segment_id","resource_type"),
	CONSTRAINT "uk_demand_id_activity" UNIQUE("id","activity_id")
);
--> statement-breakpoint
CREATE TABLE "seat_assignment" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "seat_assignment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"plan_id" bigint NOT NULL,
	"segment_id" bigint NOT NULL,
	"segment_seat_id" bigint NOT NULL,
	"occupant_type" text DEFAULT 'person' NOT NULL,
	"segment_member_id" bigint,
	"organization_id" bigint,
	"assigned_by" text,
	"assigned_at" timestamp with time zone DEFAULT now() NOT NULL,
	"revoked_by" text,
	"revoked_at" timestamp with time zone,
	CONSTRAINT "chk_seat_assignment_occupant" CHECK ((
        ("seat_assignment"."occupant_type" = 'person'
          and "seat_assignment"."segment_member_id" is not null
          and "seat_assignment"."organization_id" is null)
        or
        ("seat_assignment"."occupant_type" = 'organization'
          and "seat_assignment"."segment_member_id" is null
          and "seat_assignment"."organization_id" is not null)
      ))
);
--> statement-breakpoint
CREATE TABLE "segment_seat" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "segment_seat_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"plan_id" bigint NOT NULL,
	"external_id" text NOT NULL,
	"source_external_id" text,
	"label" text NOT NULL,
	"kind" text DEFAULT 'seat' NOT NULL,
	"rank" text DEFAULT 'normal' NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"ordinal" integer DEFAULT 0 NOT NULL,
	"removed_at" timestamp with time zone,
	CONSTRAINT "uk_segment_seat_external" UNIQUE("plan_id","external_id"),
	CONSTRAINT "uk_segment_seat_id_plan" UNIQUE("id","plan_id")
);
--> statement-breakpoint
CREATE TABLE "segment_seating_layout" (
	"plan_id" bigint PRIMARY KEY NOT NULL,
	"renderer_kind" text NOT NULL,
	"renderer_version" integer NOT NULL,
	"data" jsonb NOT NULL,
	"updated_by" text,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "segment_seating_log" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "segment_seating_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"plan_id" bigint NOT NULL,
	"action" text NOT NULL,
	"payload" jsonb,
	"operator_id" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "segment_seating_plan" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "segment_seating_plan_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"segment_id" bigint NOT NULL,
	"activity_id" bigint NOT NULL,
	"activity_venue_zone_id" bigint NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"version" integer DEFAULT 0 NOT NULL,
	"rejected_reason" text,
	"saved_by" text,
	"saved_at" timestamp with time zone,
	"confirmed_by" text,
	"confirmed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "uk_seating_plan_id_segment" UNIQUE("id","segment_id")
);
--> statement-breakpoint
CREATE TABLE "supplier" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "supplier_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"service_categories" text[] NOT NULL,
	"city" text NOT NULL,
	"contact_person" text NOT NULL,
	"contact_phone" text NOT NULL,
	"status" text DEFAULT 'enabled' NOT NULL,
	"remark" text,
	"created_by" text,
	"updated_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "supplier_quote" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "supplier_quote_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"supplier_id" bigint NOT NULL,
	"file_id" uuid NOT NULL,
	"uploaded_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "member_trip" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "member_trip_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"project_id" bigint NOT NULL,
	"activity_id" bigint NOT NULL,
	"activity_member_id" bigint NOT NULL,
	"member_id" bigint NOT NULL,
	"segment_id" bigint,
	"transport_mode" text NOT NULL,
	"service_number" text,
	"departure_time" timestamp with time zone NOT NULL,
	"arrival_time" timestamp with time zone NOT NULL,
	"departure_location" text NOT NULL,
	"destination" text NOT NULL,
	"created_by" text,
	"updated_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "chk_member_trip_time_range" CHECK ("member_trip"."departure_time" < "member_trip"."arrival_time")
);
--> statement-breakpoint
CREATE TABLE "activity_venue" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "activity_venue_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"activity_id" bigint NOT NULL,
	"source_venue_id" bigint,
	"name" text NOT NULL,
	"address" text,
	"note" text,
	"status" text DEFAULT 'active' NOT NULL,
	"ordinal" integer DEFAULT 0 NOT NULL,
	"created_by" text,
	"updated_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "uk_activity_venue_source" UNIQUE("activity_id","source_venue_id"),
	CONSTRAINT "uk_activity_venue_id_activity" UNIQUE("id","activity_id")
);
--> statement-breakpoint
CREATE TABLE "activity_venue_layout" (
	"activity_venue_id" bigint PRIMARY KEY NOT NULL,
	"renderer_kind" text NOT NULL,
	"renderer_version" integer NOT NULL,
	"data" jsonb NOT NULL,
	"updated_by" text,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "activity_venue_zone" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "activity_venue_zone_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"activity_venue_id" bigint NOT NULL,
	"activity_id" bigint NOT NULL,
	"source_zone_id" bigint,
	"external_id" text NOT NULL,
	"name" text NOT NULL,
	"kind" text NOT NULL,
	"purpose" text NOT NULL,
	"capacity" integer DEFAULT 0 NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"note" text,
	"ordinal" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "uk_activity_venue_zone_external" UNIQUE("activity_venue_id","external_id"),
	CONSTRAINT "uk_activity_venue_zone_id_activity" UNIQUE("id","activity_id")
);
--> statement-breakpoint
CREATE TABLE "venue" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "venue_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"address" text,
	"description" text,
	"status" text DEFAULT 'enabled' NOT NULL,
	"created_by" text,
	"updated_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "venue_layout" (
	"venue_id" bigint PRIMARY KEY NOT NULL,
	"renderer_kind" text NOT NULL,
	"renderer_version" integer NOT NULL,
	"data" jsonb NOT NULL,
	"updated_by" text,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "venue_seat" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "venue_seat_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"venue_id" bigint NOT NULL,
	"zone_id" bigint NOT NULL,
	"external_id" text NOT NULL,
	"label" text NOT NULL,
	"kind" text DEFAULT 'seat' NOT NULL,
	"rank" text DEFAULT 'normal' NOT NULL,
	"ordinal" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "uk_venue_seat_external" UNIQUE("venue_id","external_id")
);
--> statement-breakpoint
CREATE TABLE "venue_zone" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "venue_zone_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"venue_id" bigint NOT NULL,
	"external_id" text NOT NULL,
	"name" text NOT NULL,
	"kind" text NOT NULL,
	"ordinal" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "uk_venue_zone_external" UNIQUE("venue_id","external_id"),
	CONSTRAINT "uk_venue_zone_id_venue" UNIQUE("id","venue_id")
);
--> statement-breakpoint
ALTER TABLE "activity_segment" ADD CONSTRAINT "activity_segment_activity_id_activity_id_fk" FOREIGN KEY ("activity_id") REFERENCES "public"."activity"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_segment" ADD CONSTRAINT "activity_segment_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_segment" ADD CONSTRAINT "activity_segment_updated_by_user_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_segment" ADD CONSTRAINT "fk_segment_line_activity" FOREIGN KEY ("agenda_line_id","activity_id") REFERENCES "public"."activity_agenda_line"("id","activity_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_segment_revision" ADD CONSTRAINT "activity_segment_revision_changed_by_user_id_fk" FOREIGN KEY ("changed_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_agenda_line" ADD CONSTRAINT "activity_agenda_line_activity_id_activity_id_fk" FOREIGN KEY ("activity_id") REFERENCES "public"."activity"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_agenda_line" ADD CONSTRAINT "activity_agenda_line_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_agenda_line" ADD CONSTRAINT "activity_agenda_line_updated_by_user_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "account" ADD CONSTRAINT "account_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session" ADD CONSTRAINT "session_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "file_asset" ADD CONSTRAINT "file_asset_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invitation_batch" ADD CONSTRAINT "invitation_batch_activity_id_activity_id_fk" FOREIGN KEY ("activity_id") REFERENCES "public"."activity"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invitation_batch" ADD CONSTRAINT "invitation_batch_template_id_invitation_template_id_fk" FOREIGN KEY ("template_id") REFERENCES "public"."invitation_template"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invitation_batch" ADD CONSTRAINT "invitation_batch_template_file_id_file_asset_id_fk" FOREIGN KEY ("template_file_id") REFERENCES "public"."file_asset"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invitation_batch" ADD CONSTRAINT "invitation_batch_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invitation_download_log" ADD CONSTRAINT "invitation_download_log_downloaded_by_user_id_fk" FOREIGN KEY ("downloaded_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invitation_record" ADD CONSTRAINT "invitation_record_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invitation_record" ADD CONSTRAINT "invitation_record_batch_id_invitation_batch_id_fk" FOREIGN KEY ("batch_id") REFERENCES "public"."invitation_batch"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invitation_record" ADD CONSTRAINT "fk_invitation_record_activity_member" FOREIGN KEY ("activity_id","member_id") REFERENCES "public"."activity_member"("activity_id","member_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invitation_template" ADD CONSTRAINT "invitation_template_template_file_id_file_asset_id_fk" FOREIGN KEY ("template_file_id") REFERENCES "public"."file_asset"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invitation_template" ADD CONSTRAINT "invitation_template_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invitation_template" ADD CONSTRAINT "invitation_template_updated_by_user_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_member" ADD CONSTRAINT "activity_member_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_member" ADD CONSTRAINT "activity_member_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_member" ADD CONSTRAINT "activity_member_updated_by_user_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_member" ADD CONSTRAINT "fk_activity_member_activity" FOREIGN KEY ("activity_id","project_id") REFERENCES "public"."activity"("id","project_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_member" ADD CONSTRAINT "fk_activity_member_project_member" FOREIGN KEY ("project_member_id","project_id","member_id") REFERENCES "public"."project_member"("id","project_id","member_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "member" ADD CONSTRAINT "member_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "member" ADD CONSTRAINT "member_merged_into_id_member_id_fk" FOREIGN KEY ("merged_into_id") REFERENCES "public"."member"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "member" ADD CONSTRAINT "member_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "member" ADD CONSTRAINT "member_updated_by_user_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "project_member" ADD CONSTRAINT "project_member_project_id_project_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."project"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "project_member" ADD CONSTRAINT "project_member_member_id_member_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."member"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "project_member" ADD CONSTRAINT "project_member_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "project_member" ADD CONSTRAINT "project_member_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "project_member" ADD CONSTRAINT "project_member_updated_by_user_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "segment_member" ADD CONSTRAINT "segment_member_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "segment_member" ADD CONSTRAINT "segment_member_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "segment_member" ADD CONSTRAINT "segment_member_updated_by_user_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "segment_member" ADD CONSTRAINT "fk_segment_member_segment" FOREIGN KEY ("segment_id","activity_id") REFERENCES "public"."activity_segment"("id","activity_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "segment_member" ADD CONSTRAINT "fk_segment_member_activity_member" FOREIGN KEY ("activity_member_id","activity_id","member_id") REFERENCES "public"."activity_member"("id","activity_id","member_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "organization" ADD CONSTRAINT "organization_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "organization" ADD CONSTRAINT "organization_updated_by_user_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity" ADD CONSTRAINT "activity_project_id_project_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."project"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity" ADD CONSTRAINT "activity_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity" ADD CONSTRAINT "activity_updated_by_user_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_media" ADD CONSTRAINT "activity_media_activity_id_activity_id_fk" FOREIGN KEY ("activity_id") REFERENCES "public"."activity"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_media" ADD CONSTRAINT "activity_media_file_id_file_asset_id_fk" FOREIGN KEY ("file_id") REFERENCES "public"."file_asset"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_media" ADD CONSTRAINT "activity_media_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "project" ADD CONSTRAINT "project_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "project" ADD CONSTRAINT "project_updated_by_user_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_resource" ADD CONSTRAINT "activity_resource_activity_id_activity_id_fk" FOREIGN KEY ("activity_id") REFERENCES "public"."activity"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_resource" ADD CONSTRAINT "activity_resource_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_resource" ADD CONSTRAINT "activity_resource_updated_by_user_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "resource_demand_link" ADD CONSTRAINT "resource_demand_link_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "resource_demand_link" ADD CONSTRAINT "fk_link_demand_activity" FOREIGN KEY ("demand_id","activity_id") REFERENCES "public"."segment_resource_demand"("id","activity_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "resource_demand_link" ADD CONSTRAINT "fk_link_resource_activity" FOREIGN KEY ("resource_id","activity_id") REFERENCES "public"."activity_resource"("id","activity_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "resource_member_binding" ADD CONSTRAINT "resource_member_binding_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "resource_member_binding" ADD CONSTRAINT "fk_binding_resource_activity" FOREIGN KEY ("resource_id","activity_id") REFERENCES "public"."activity_resource"("id","activity_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "resource_member_binding" ADD CONSTRAINT "fk_binding_activity_member" FOREIGN KEY ("activity_member_id","activity_id","member_id") REFERENCES "public"."activity_member"("id","activity_id","member_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "segment_resource_demand" ADD CONSTRAINT "segment_resource_demand_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "segment_resource_demand" ADD CONSTRAINT "segment_resource_demand_updated_by_user_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "segment_resource_demand" ADD CONSTRAINT "fk_demand_segment_activity" FOREIGN KEY ("segment_id","activity_id") REFERENCES "public"."activity_segment"("id","activity_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "seat_assignment" ADD CONSTRAINT "seat_assignment_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "seat_assignment" ADD CONSTRAINT "seat_assignment_assigned_by_user_id_fk" FOREIGN KEY ("assigned_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "seat_assignment" ADD CONSTRAINT "seat_assignment_revoked_by_user_id_fk" FOREIGN KEY ("revoked_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "seat_assignment" ADD CONSTRAINT "fk_seat_assignment_seat" FOREIGN KEY ("segment_seat_id","plan_id") REFERENCES "public"."segment_seat"("id","plan_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "seat_assignment" ADD CONSTRAINT "fk_seat_assignment_plan" FOREIGN KEY ("plan_id","segment_id") REFERENCES "public"."segment_seating_plan"("id","segment_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "seat_assignment" ADD CONSTRAINT "fk_seat_assignment_member" FOREIGN KEY ("segment_member_id","segment_id") REFERENCES "public"."segment_member"("id","segment_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "segment_seat" ADD CONSTRAINT "segment_seat_plan_id_segment_seating_plan_id_fk" FOREIGN KEY ("plan_id") REFERENCES "public"."segment_seating_plan"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "segment_seating_layout" ADD CONSTRAINT "segment_seating_layout_plan_id_segment_seating_plan_id_fk" FOREIGN KEY ("plan_id") REFERENCES "public"."segment_seating_plan"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "segment_seating_layout" ADD CONSTRAINT "segment_seating_layout_updated_by_user_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "segment_seating_log" ADD CONSTRAINT "segment_seating_log_plan_id_segment_seating_plan_id_fk" FOREIGN KEY ("plan_id") REFERENCES "public"."segment_seating_plan"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "segment_seating_log" ADD CONSTRAINT "segment_seating_log_operator_id_user_id_fk" FOREIGN KEY ("operator_id") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "segment_seating_plan" ADD CONSTRAINT "segment_seating_plan_saved_by_user_id_fk" FOREIGN KEY ("saved_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "segment_seating_plan" ADD CONSTRAINT "segment_seating_plan_confirmed_by_user_id_fk" FOREIGN KEY ("confirmed_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "segment_seating_plan" ADD CONSTRAINT "fk_seating_plan_segment" FOREIGN KEY ("segment_id","activity_id") REFERENCES "public"."activity_segment"("id","activity_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "segment_seating_plan" ADD CONSTRAINT "fk_seating_plan_zone" FOREIGN KEY ("activity_venue_zone_id","activity_id") REFERENCES "public"."activity_venue_zone"("id","activity_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "supplier" ADD CONSTRAINT "supplier_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "supplier" ADD CONSTRAINT "supplier_updated_by_user_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "supplier_quote" ADD CONSTRAINT "supplier_quote_supplier_id_supplier_id_fk" FOREIGN KEY ("supplier_id") REFERENCES "public"."supplier"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "supplier_quote" ADD CONSTRAINT "supplier_quote_file_id_file_asset_id_fk" FOREIGN KEY ("file_id") REFERENCES "public"."file_asset"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "supplier_quote" ADD CONSTRAINT "supplier_quote_uploaded_by_user_id_fk" FOREIGN KEY ("uploaded_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "member_trip" ADD CONSTRAINT "member_trip_project_id_project_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."project"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "member_trip" ADD CONSTRAINT "member_trip_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "member_trip" ADD CONSTRAINT "member_trip_updated_by_user_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "member_trip" ADD CONSTRAINT "fk_member_trip_activity" FOREIGN KEY ("activity_id","project_id") REFERENCES "public"."activity"("id","project_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "member_trip" ADD CONSTRAINT "fk_member_trip_activity_member" FOREIGN KEY ("activity_member_id","activity_id","member_id") REFERENCES "public"."activity_member"("id","activity_id","member_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "member_trip" ADD CONSTRAINT "fk_member_trip_segment" FOREIGN KEY ("segment_id","activity_id") REFERENCES "public"."activity_segment"("id","activity_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_venue" ADD CONSTRAINT "activity_venue_activity_id_activity_id_fk" FOREIGN KEY ("activity_id") REFERENCES "public"."activity"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_venue" ADD CONSTRAINT "activity_venue_source_venue_id_venue_id_fk" FOREIGN KEY ("source_venue_id") REFERENCES "public"."venue"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_venue" ADD CONSTRAINT "activity_venue_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_venue" ADD CONSTRAINT "activity_venue_updated_by_user_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_venue_layout" ADD CONSTRAINT "activity_venue_layout_activity_venue_id_activity_venue_id_fk" FOREIGN KEY ("activity_venue_id") REFERENCES "public"."activity_venue"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_venue_layout" ADD CONSTRAINT "activity_venue_layout_updated_by_user_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_venue_zone" ADD CONSTRAINT "fk_activity_venue_zone_venue" FOREIGN KEY ("activity_venue_id","activity_id") REFERENCES "public"."activity_venue"("id","activity_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "venue" ADD CONSTRAINT "venue_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "venue" ADD CONSTRAINT "venue_updated_by_user_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "venue_layout" ADD CONSTRAINT "venue_layout_venue_id_venue_id_fk" FOREIGN KEY ("venue_id") REFERENCES "public"."venue"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "venue_layout" ADD CONSTRAINT "venue_layout_updated_by_user_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "venue_seat" ADD CONSTRAINT "fk_venue_seat_zone" FOREIGN KEY ("zone_id","venue_id") REFERENCES "public"."venue_zone"("id","venue_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "venue_zone" ADD CONSTRAINT "venue_zone_venue_id_venue_id_fk" FOREIGN KEY ("venue_id") REFERENCES "public"."venue"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_segment_activity" ON "activity_segment" USING btree ("activity_id");--> statement-breakpoint
CREATE INDEX "idx_segment_line" ON "activity_segment" USING btree ("agenda_line_id");--> statement-breakpoint
CREATE INDEX "idx_agenda_line_activity" ON "activity_agenda_line" USING btree ("activity_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uk_agenda_line_main" ON "activity_agenda_line" USING btree ("activity_id") WHERE "activity_agenda_line"."line_type" = 'main';--> statement-breakpoint
CREATE INDEX "account_userId_idx" ON "account" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "session_userId_idx" ON "session" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "verification_identifier_idx" ON "verification" USING btree ("identifier");--> statement-breakpoint
CREATE INDEX "idx_invitation_batch_activity" ON "invitation_batch" USING btree ("activity_id");--> statement-breakpoint
CREATE INDEX "idx_invitation_record_batch" ON "invitation_record" USING btree ("batch_id");--> statement-breakpoint
CREATE INDEX "idx_activity_member_member" ON "activity_member" USING btree ("member_id");--> statement-breakpoint
CREATE INDEX "idx_activity_member_project" ON "activity_member" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "idx_activity_member_organization_activity" ON "activity_member" USING btree ("organization_id","activity_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uk_member_id_document" ON "member" USING btree ("id_type","id_number") WHERE "member"."id_type" is not null and "member"."id_number" is not null;--> statement-breakpoint
CREATE INDEX "idx_member_organization" ON "member" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_project_member_member" ON "project_member" USING btree ("member_id");--> statement-breakpoint
CREATE INDEX "idx_project_member_organization_project" ON "project_member" USING btree ("organization_id","project_id");--> statement-breakpoint
CREATE INDEX "idx_segment_member_member" ON "segment_member" USING btree ("member_id");--> statement-breakpoint
CREATE INDEX "idx_segment_member_activity" ON "segment_member" USING btree ("activity_id");--> statement-breakpoint
CREATE INDEX "idx_segment_member_organization_segment" ON "segment_member" USING btree ("organization_id","segment_id");--> statement-breakpoint
CREATE INDEX "idx_activity_project" ON "activity" USING btree ("project_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uk_activity_media" ON "activity_media" USING btree ("activity_id","file_id");--> statement-breakpoint
CREATE INDEX "idx_resource_activity" ON "activity_resource" USING btree ("activity_id");--> statement-breakpoint
CREATE INDEX "idx_link_resource" ON "resource_demand_link" USING btree ("resource_id");--> statement-breakpoint
CREATE INDEX "idx_binding_activity_member" ON "resource_member_binding" USING btree ("activity_member_id");--> statement-breakpoint
CREATE INDEX "idx_demand_activity" ON "segment_resource_demand" USING btree ("activity_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uk_seat_assignment_seat" ON "seat_assignment" USING btree ("segment_seat_id") WHERE "seat_assignment"."revoked_at" is null;--> statement-breakpoint
CREATE UNIQUE INDEX "uk_seat_assignment_member" ON "seat_assignment" USING btree ("plan_id","segment_member_id") WHERE "seat_assignment"."revoked_at" is null and "seat_assignment"."segment_member_id" is not null;--> statement-breakpoint
CREATE UNIQUE INDEX "uk_segment_seat_label" ON "segment_seat" USING btree ("plan_id","label") WHERE "segment_seat"."removed_at" is null;--> statement-breakpoint
CREATE INDEX "idx_seating_log_plan" ON "segment_seating_log" USING btree ("plan_id");--> statement-breakpoint
CREATE INDEX "idx_seating_plan_activity" ON "segment_seating_plan" USING btree ("activity_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uk_seating_plan_segment" ON "segment_seating_plan" USING btree ("segment_id") WHERE "segment_seating_plan"."status" <> 'voided';--> statement-breakpoint
CREATE INDEX "idx_member_trip_activity" ON "member_trip" USING btree ("activity_id");--> statement-breakpoint
CREATE INDEX "idx_member_trip_member" ON "member_trip" USING btree ("member_id");--> statement-breakpoint
CREATE INDEX "idx_activity_venue_activity" ON "activity_venue" USING btree ("activity_id");--> statement-breakpoint
CREATE INDEX "idx_activity_venue_zone_activity" ON "activity_venue_zone" USING btree ("activity_id");