/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedSplatRouteImport } from './routes/_authenticated/$'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMemberIndexRouteImport } from './routes/_authenticated/member/index'
import { Route as AuthenticatedProjectListRouteImport } from './routes/_authenticated/project/list'
import { Route as AuthenticatedSupplierIndexRouteImport } from './routes/_authenticated/supplier/index'
import { Route as AuthenticatedSystemRoleRouteImport } from './routes/_authenticated/system/role'
import { Route as AuthenticatedSystemUserRouteImport } from './routes/_authenticated/system/user'
import { Route as AuthenticatedInvitationBatchIndexRouteImport } from './routes/_authenticated/invitation/batch/index'
import { Route as AuthenticatedInvitationGenerateIndexRouteImport } from './routes/_authenticated/invitation/generate/index'
import { Route as AuthenticatedInvitationTemplateIndexRouteImport } from './routes/_authenticated/invitation/template/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSplatRoute = AuthenticatedSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMemberIndexRoute =
  AuthenticatedMemberIndexRouteImport.update({
    id: '/member/',
    path: '/member/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectListRoute =
  AuthenticatedProjectListRouteImport.update({
    id: '/project/list',
    path: '/project/list',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSupplierIndexRoute =
  AuthenticatedSupplierIndexRouteImport.update({
    id: '/supplier/',
    path: '/supplier/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSystemRoleRoute = AuthenticatedSystemRoleRouteImport.update({
  id: '/system/role',
  path: '/system/role',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSystemUserRoute = AuthenticatedSystemUserRouteImport.update({
  id: '/system/user',
  path: '/system/user',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvitationBatchIndexRoute =
  AuthenticatedInvitationBatchIndexRouteImport.update({
    id: '/invitation/batch/',
    path: '/invitation/batch/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvitationGenerateIndexRoute =
  AuthenticatedInvitationGenerateIndexRouteImport.update({
    id: '/invitation/generate/',
    path: '/invitation/generate/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvitationTemplateIndexRoute =
  AuthenticatedInvitationTemplateIndexRouteImport.update({
    id: '/invitation/template/',
    path: '/invitation/template/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$': typeof AuthenticatedSplatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/project/list': typeof AuthenticatedProjectListRoute
  '/system/role': typeof AuthenticatedSystemRoleRoute
  '/system/user': typeof AuthenticatedSystemUserRoute
  '/member/': typeof AuthenticatedMemberIndexRoute
  '/supplier/': typeof AuthenticatedSupplierIndexRoute
  '/invitation/batch/': typeof AuthenticatedInvitationBatchIndexRoute
  '/invitation/generate/': typeof AuthenticatedInvitationGenerateIndexRoute
  '/invitation/template/': typeof AuthenticatedInvitationTemplateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$': typeof AuthenticatedSplatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/project/list': typeof AuthenticatedProjectListRoute
  '/system/role': typeof AuthenticatedSystemRoleRoute
  '/system/user': typeof AuthenticatedSystemUserRoute
  '/member': typeof AuthenticatedMemberIndexRoute
  '/supplier': typeof AuthenticatedSupplierIndexRoute
  '/invitation/batch': typeof AuthenticatedInvitationBatchIndexRoute
  '/invitation/generate': typeof AuthenticatedInvitationGenerateIndexRoute
  '/invitation/template': typeof AuthenticatedInvitationTemplateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/$': typeof AuthenticatedSplatRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/project/list': typeof AuthenticatedProjectListRoute
  '/_authenticated/system/role': typeof AuthenticatedSystemRoleRoute
  '/_authenticated/system/user': typeof AuthenticatedSystemUserRoute
  '/_authenticated/member/': typeof AuthenticatedMemberIndexRoute
  '/_authenticated/supplier/': typeof AuthenticatedSupplierIndexRoute
  '/_authenticated/invitation/batch/': typeof AuthenticatedInvitationBatchIndexRoute
  '/_authenticated/invitation/generate/': typeof AuthenticatedInvitationGenerateIndexRoute
  '/_authenticated/invitation/template/': typeof AuthenticatedInvitationTemplateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$'
    | '/dashboard'
    | '/project/list'
    | '/system/role'
    | '/system/user'
    | '/member/'
    | '/supplier/'
    | '/invitation/batch/'
    | '/invitation/generate/'
    | '/invitation/template/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/$'
    | '/dashboard'
    | '/project/list'
    | '/system/role'
    | '/system/user'
    | '/member'
    | '/supplier'
    | '/invitation/batch'
    | '/invitation/generate'
    | '/invitation/template'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/$'
    | '/_authenticated/dashboard'
    | '/_authenticated/project/list'
    | '/_authenticated/system/role'
    | '/_authenticated/system/user'
    | '/_authenticated/member/'
    | '/_authenticated/supplier/'
    | '/_authenticated/invitation/batch/'
    | '/_authenticated/invitation/generate/'
    | '/_authenticated/invitation/template/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/$': {
      id: '/_authenticated/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AuthenticatedSplatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/member/': {
      id: '/_authenticated/member/'
      path: '/member'
      fullPath: '/member/'
      preLoaderRoute: typeof AuthenticatedMemberIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/project/list': {
      id: '/_authenticated/project/list'
      path: '/project/list'
      fullPath: '/project/list'
      preLoaderRoute: typeof AuthenticatedProjectListRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/supplier/': {
      id: '/_authenticated/supplier/'
      path: '/supplier'
      fullPath: '/supplier/'
      preLoaderRoute: typeof AuthenticatedSupplierIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/system/role': {
      id: '/_authenticated/system/role'
      path: '/system/role'
      fullPath: '/system/role'
      preLoaderRoute: typeof AuthenticatedSystemRoleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/system/user': {
      id: '/_authenticated/system/user'
      path: '/system/user'
      fullPath: '/system/user'
      preLoaderRoute: typeof AuthenticatedSystemUserRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invitation/batch/': {
      id: '/_authenticated/invitation/batch/'
      path: '/invitation/batch'
      fullPath: '/invitation/batch/'
      preLoaderRoute: typeof AuthenticatedInvitationBatchIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invitation/generate/': {
      id: '/_authenticated/invitation/generate/'
      path: '/invitation/generate'
      fullPath: '/invitation/generate/'
      preLoaderRoute: typeof AuthenticatedInvitationGenerateIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invitation/template/': {
      id: '/_authenticated/invitation/template/'
      path: '/invitation/template'
      fullPath: '/invitation/template/'
      preLoaderRoute: typeof AuthenticatedInvitationTemplateIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedSplatRoute: typeof AuthenticatedSplatRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProjectListRoute: typeof AuthenticatedProjectListRoute
  AuthenticatedSystemRoleRoute: typeof AuthenticatedSystemRoleRoute
  AuthenticatedSystemUserRoute: typeof AuthenticatedSystemUserRoute
  AuthenticatedMemberIndexRoute: typeof AuthenticatedMemberIndexRoute
  AuthenticatedSupplierIndexRoute: typeof AuthenticatedSupplierIndexRoute
  AuthenticatedInvitationBatchIndexRoute: typeof AuthenticatedInvitationBatchIndexRoute
  AuthenticatedInvitationGenerateIndexRoute: typeof AuthenticatedInvitationGenerateIndexRoute
  AuthenticatedInvitationTemplateIndexRoute: typeof AuthenticatedInvitationTemplateIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSplatRoute: AuthenticatedSplatRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProjectListRoute: AuthenticatedProjectListRoute,
  AuthenticatedSystemRoleRoute: AuthenticatedSystemRoleRoute,
  AuthenticatedSystemUserRoute: AuthenticatedSystemUserRoute,
  AuthenticatedMemberIndexRoute: AuthenticatedMemberIndexRoute,
  AuthenticatedSupplierIndexRoute: AuthenticatedSupplierIndexRoute,
  AuthenticatedInvitationBatchIndexRoute:
    AuthenticatedInvitationBatchIndexRoute,
  AuthenticatedInvitationGenerateIndexRoute:
    AuthenticatedInvitationGenerateIndexRoute,
  AuthenticatedInvitationTemplateIndexRoute:
    AuthenticatedInvitationTemplateIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
