/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedSplatRouteImport } from './routes/_authenticated/$'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMemberIndexRouteImport } from './routes/_authenticated/member/index'
import { Route as AuthenticatedProjectProjectIdRouteImport } from './routes/_authenticated/project/$projectId'
import { Route as AuthenticatedProjectListRouteImport } from './routes/_authenticated/project/list'
import { Route as AuthenticatedSupplierIndexRouteImport } from './routes/_authenticated/supplier/index'
import { Route as AuthenticatedSystemRoleRouteImport } from './routes/_authenticated/system/role'
import { Route as AuthenticatedSystemUserRouteImport } from './routes/_authenticated/system/user'
import { Route as AuthenticatedInvitationTemplateIndexRouteImport } from './routes/_authenticated/invitation/template/index'
import { Route as AuthenticatedProjectProjectIdIndexRouteImport } from './routes/_authenticated/project/$projectId.index'
import { Route as AuthenticatedProjectProjectIdMembersRouteImport } from './routes/_authenticated/project/$projectId.members'
import { Route as AuthenticatedSupplierSupplierIdQuoteRouteImport } from './routes/_authenticated/supplier/$supplierId.quote'
import { Route as AuthenticatedProjectProjectIdActivityActivityIdRouteImport } from './routes/_authenticated/project/$projectId_.activity.$activityId'
import { Route as AuthenticatedProjectProjectIdActivityActivityIdIndexRouteImport } from './routes/_authenticated/project/$projectId_.activity.$activityId.index'
import { Route as AuthenticatedProjectProjectIdActivityActivityIdConfigRouteImport } from './routes/_authenticated/project/$projectId_.activity.$activityId.config'
import { Route as AuthenticatedProjectProjectIdActivityActivityIdMembersRouteImport } from './routes/_authenticated/project/$projectId_.activity.$activityId.members'
import { Route as AuthenticatedProjectProjectIdActivityActivityIdRegistrationRouteImport } from './routes/_authenticated/project/$projectId_.activity.$activityId.registration'
import { Route as AuthenticatedProjectProjectIdActivityActivityIdResourcesRouteImport } from './routes/_authenticated/project/$projectId_.activity.$activityId.resources'
import { Route as AuthenticatedProjectProjectIdActivityActivityIdSeatingRouteImport } from './routes/_authenticated/project/$projectId_.activity.$activityId.seating'
import { Route as AuthenticatedProjectProjectIdActivityActivityIdVenueRouteImport } from './routes/_authenticated/project/$projectId_.activity.$activityId.venue'
import { Route as AuthenticatedProjectProjectIdActivityActivityIdAgendaIndexRouteImport } from './routes/_authenticated/project/$projectId_.activity.$activityId.agenda/index'
import { Route as AuthenticatedProjectProjectIdActivityActivityIdInvitationsIndexRouteImport } from './routes/_authenticated/project/$projectId_.activity.$activityId.invitations/index'
import { Route as AuthenticatedProjectProjectIdActivityActivityIdInvitationsGenerateRouteImport } from './routes/_authenticated/project/$projectId_.activity.$activityId.invitations.generate'
import { Route as AuthenticatedProjectProjectIdActivityActivityIdResourceLedgerIndexRouteImport } from './routes/_authenticated/project/$projectId_.activity.$activityId.resource-ledger/index'
import { Route as AuthenticatedProjectProjectIdActivityActivityIdTripIndexRouteImport } from './routes/_authenticated/project/$projectId_.activity.$activityId.trip/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSplatRoute = AuthenticatedSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMemberIndexRoute =
  AuthenticatedMemberIndexRouteImport.update({
    id: '/member/',
    path: '/member/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectProjectIdRoute =
  AuthenticatedProjectProjectIdRouteImport.update({
    id: '/project/$projectId',
    path: '/project/$projectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectListRoute =
  AuthenticatedProjectListRouteImport.update({
    id: '/project/list',
    path: '/project/list',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSupplierIndexRoute =
  AuthenticatedSupplierIndexRouteImport.update({
    id: '/supplier/',
    path: '/supplier/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSystemRoleRoute = AuthenticatedSystemRoleRouteImport.update({
  id: '/system/role',
  path: '/system/role',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSystemUserRoute = AuthenticatedSystemUserRouteImport.update({
  id: '/system/user',
  path: '/system/user',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvitationTemplateIndexRoute =
  AuthenticatedInvitationTemplateIndexRouteImport.update({
    id: '/invitation/template/',
    path: '/invitation/template/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectProjectIdIndexRoute =
  AuthenticatedProjectProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectProjectIdRoute,
  } as any)
const AuthenticatedProjectProjectIdMembersRoute =
  AuthenticatedProjectProjectIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedProjectProjectIdRoute,
  } as any)
const AuthenticatedSupplierSupplierIdQuoteRoute =
  AuthenticatedSupplierSupplierIdQuoteRouteImport.update({
    id: '/supplier/$supplierId/quote',
    path: '/supplier/$supplierId/quote',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectProjectIdActivityActivityIdRoute =
  AuthenticatedProjectProjectIdActivityActivityIdRouteImport.update({
    id: '/project/$projectId_/activity/$activityId',
    path: '/project/$projectId/activity/$activityId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectProjectIdActivityActivityIdIndexRoute =
  AuthenticatedProjectProjectIdActivityActivityIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectProjectIdActivityActivityIdRoute,
  } as any)
const AuthenticatedProjectProjectIdActivityActivityIdConfigRoute =
  AuthenticatedProjectProjectIdActivityActivityIdConfigRouteImport.update({
    id: '/config',
    path: '/config',
    getParentRoute: () => AuthenticatedProjectProjectIdActivityActivityIdRoute,
  } as any)
const AuthenticatedProjectProjectIdActivityActivityIdMembersRoute =
  AuthenticatedProjectProjectIdActivityActivityIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedProjectProjectIdActivityActivityIdRoute,
  } as any)
const AuthenticatedProjectProjectIdActivityActivityIdRegistrationRoute =
  AuthenticatedProjectProjectIdActivityActivityIdRegistrationRouteImport.update(
    {
      id: '/registration',
      path: '/registration',
      getParentRoute: () =>
        AuthenticatedProjectProjectIdActivityActivityIdRoute,
    } as any,
  )
const AuthenticatedProjectProjectIdActivityActivityIdResourcesRoute =
  AuthenticatedProjectProjectIdActivityActivityIdResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => AuthenticatedProjectProjectIdActivityActivityIdRoute,
  } as any)
const AuthenticatedProjectProjectIdActivityActivityIdSeatingRoute =
  AuthenticatedProjectProjectIdActivityActivityIdSeatingRouteImport.update({
    id: '/seating',
    path: '/seating',
    getParentRoute: () => AuthenticatedProjectProjectIdActivityActivityIdRoute,
  } as any)
const AuthenticatedProjectProjectIdActivityActivityIdVenueRoute =
  AuthenticatedProjectProjectIdActivityActivityIdVenueRouteImport.update({
    id: '/venue',
    path: '/venue',
    getParentRoute: () => AuthenticatedProjectProjectIdActivityActivityIdRoute,
  } as any)
const AuthenticatedProjectProjectIdActivityActivityIdAgendaIndexRoute =
  AuthenticatedProjectProjectIdActivityActivityIdAgendaIndexRouteImport.update({
    id: '/agenda/',
    path: '/agenda/',
    getParentRoute: () => AuthenticatedProjectProjectIdActivityActivityIdRoute,
  } as any)
const AuthenticatedProjectProjectIdActivityActivityIdInvitationsIndexRoute =
  AuthenticatedProjectProjectIdActivityActivityIdInvitationsIndexRouteImport.update(
    {
      id: '/invitations/',
      path: '/invitations/',
      getParentRoute: () =>
        AuthenticatedProjectProjectIdActivityActivityIdRoute,
    } as any,
  )
const AuthenticatedProjectProjectIdActivityActivityIdInvitationsGenerateRoute =
  AuthenticatedProjectProjectIdActivityActivityIdInvitationsGenerateRouteImport.update(
    {
      id: '/invitations/generate',
      path: '/invitations/generate',
      getParentRoute: () =>
        AuthenticatedProjectProjectIdActivityActivityIdRoute,
    } as any,
  )
const AuthenticatedProjectProjectIdActivityActivityIdResourceLedgerIndexRoute =
  AuthenticatedProjectProjectIdActivityActivityIdResourceLedgerIndexRouteImport.update(
    {
      id: '/resource-ledger/',
      path: '/resource-ledger/',
      getParentRoute: () =>
        AuthenticatedProjectProjectIdActivityActivityIdRoute,
    } as any,
  )
const AuthenticatedProjectProjectIdActivityActivityIdTripIndexRoute =
  AuthenticatedProjectProjectIdActivityActivityIdTripIndexRouteImport.update({
    id: '/trip/',
    path: '/trip/',
    getParentRoute: () => AuthenticatedProjectProjectIdActivityActivityIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$': typeof AuthenticatedSplatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/project/$projectId': typeof AuthenticatedProjectProjectIdRouteWithChildren
  '/project/list': typeof AuthenticatedProjectListRoute
  '/system/role': typeof AuthenticatedSystemRoleRoute
  '/system/user': typeof AuthenticatedSystemUserRoute
  '/member/': typeof AuthenticatedMemberIndexRoute
  '/supplier/': typeof AuthenticatedSupplierIndexRoute
  '/project/$projectId/members': typeof AuthenticatedProjectProjectIdMembersRoute
  '/supplier/$supplierId/quote': typeof AuthenticatedSupplierSupplierIdQuoteRoute
  '/invitation/template/': typeof AuthenticatedInvitationTemplateIndexRoute
  '/project/$projectId/': typeof AuthenticatedProjectProjectIdIndexRoute
  '/project/$projectId/activity/$activityId': typeof AuthenticatedProjectProjectIdActivityActivityIdRouteWithChildren
  '/project/$projectId/activity/$activityId/config': typeof AuthenticatedProjectProjectIdActivityActivityIdConfigRoute
  '/project/$projectId/activity/$activityId/members': typeof AuthenticatedProjectProjectIdActivityActivityIdMembersRoute
  '/project/$projectId/activity/$activityId/registration': typeof AuthenticatedProjectProjectIdActivityActivityIdRegistrationRoute
  '/project/$projectId/activity/$activityId/resources': typeof AuthenticatedProjectProjectIdActivityActivityIdResourcesRoute
  '/project/$projectId/activity/$activityId/seating': typeof AuthenticatedProjectProjectIdActivityActivityIdSeatingRoute
  '/project/$projectId/activity/$activityId/venue': typeof AuthenticatedProjectProjectIdActivityActivityIdVenueRoute
  '/project/$projectId/activity/$activityId/': typeof AuthenticatedProjectProjectIdActivityActivityIdIndexRoute
  '/project/$projectId/activity/$activityId/invitations/generate': typeof AuthenticatedProjectProjectIdActivityActivityIdInvitationsGenerateRoute
  '/project/$projectId/activity/$activityId/agenda/': typeof AuthenticatedProjectProjectIdActivityActivityIdAgendaIndexRoute
  '/project/$projectId/activity/$activityId/invitations/': typeof AuthenticatedProjectProjectIdActivityActivityIdInvitationsIndexRoute
  '/project/$projectId/activity/$activityId/resource-ledger/': typeof AuthenticatedProjectProjectIdActivityActivityIdResourceLedgerIndexRoute
  '/project/$projectId/activity/$activityId/trip/': typeof AuthenticatedProjectProjectIdActivityActivityIdTripIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$': typeof AuthenticatedSplatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/project/list': typeof AuthenticatedProjectListRoute
  '/system/role': typeof AuthenticatedSystemRoleRoute
  '/system/user': typeof AuthenticatedSystemUserRoute
  '/member': typeof AuthenticatedMemberIndexRoute
  '/supplier': typeof AuthenticatedSupplierIndexRoute
  '/project/$projectId/members': typeof AuthenticatedProjectProjectIdMembersRoute
  '/supplier/$supplierId/quote': typeof AuthenticatedSupplierSupplierIdQuoteRoute
  '/invitation/template': typeof AuthenticatedInvitationTemplateIndexRoute
  '/project/$projectId': typeof AuthenticatedProjectProjectIdIndexRoute
  '/project/$projectId/activity/$activityId/config': typeof AuthenticatedProjectProjectIdActivityActivityIdConfigRoute
  '/project/$projectId/activity/$activityId/members': typeof AuthenticatedProjectProjectIdActivityActivityIdMembersRoute
  '/project/$projectId/activity/$activityId/registration': typeof AuthenticatedProjectProjectIdActivityActivityIdRegistrationRoute
  '/project/$projectId/activity/$activityId/resources': typeof AuthenticatedProjectProjectIdActivityActivityIdResourcesRoute
  '/project/$projectId/activity/$activityId/seating': typeof AuthenticatedProjectProjectIdActivityActivityIdSeatingRoute
  '/project/$projectId/activity/$activityId/venue': typeof AuthenticatedProjectProjectIdActivityActivityIdVenueRoute
  '/project/$projectId/activity/$activityId': typeof AuthenticatedProjectProjectIdActivityActivityIdIndexRoute
  '/project/$projectId/activity/$activityId/invitations/generate': typeof AuthenticatedProjectProjectIdActivityActivityIdInvitationsGenerateRoute
  '/project/$projectId/activity/$activityId/agenda': typeof AuthenticatedProjectProjectIdActivityActivityIdAgendaIndexRoute
  '/project/$projectId/activity/$activityId/invitations': typeof AuthenticatedProjectProjectIdActivityActivityIdInvitationsIndexRoute
  '/project/$projectId/activity/$activityId/resource-ledger': typeof AuthenticatedProjectProjectIdActivityActivityIdResourceLedgerIndexRoute
  '/project/$projectId/activity/$activityId/trip': typeof AuthenticatedProjectProjectIdActivityActivityIdTripIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/$': typeof AuthenticatedSplatRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/project/$projectId': typeof AuthenticatedProjectProjectIdRouteWithChildren
  '/_authenticated/project/list': typeof AuthenticatedProjectListRoute
  '/_authenticated/system/role': typeof AuthenticatedSystemRoleRoute
  '/_authenticated/system/user': typeof AuthenticatedSystemUserRoute
  '/_authenticated/member/': typeof AuthenticatedMemberIndexRoute
  '/_authenticated/supplier/': typeof AuthenticatedSupplierIndexRoute
  '/_authenticated/project/$projectId/members': typeof AuthenticatedProjectProjectIdMembersRoute
  '/_authenticated/supplier/$supplierId/quote': typeof AuthenticatedSupplierSupplierIdQuoteRoute
  '/_authenticated/invitation/template/': typeof AuthenticatedInvitationTemplateIndexRoute
  '/_authenticated/project/$projectId/': typeof AuthenticatedProjectProjectIdIndexRoute
  '/_authenticated/project/$projectId_/activity/$activityId': typeof AuthenticatedProjectProjectIdActivityActivityIdRouteWithChildren
  '/_authenticated/project/$projectId_/activity/$activityId/config': typeof AuthenticatedProjectProjectIdActivityActivityIdConfigRoute
  '/_authenticated/project/$projectId_/activity/$activityId/members': typeof AuthenticatedProjectProjectIdActivityActivityIdMembersRoute
  '/_authenticated/project/$projectId_/activity/$activityId/registration': typeof AuthenticatedProjectProjectIdActivityActivityIdRegistrationRoute
  '/_authenticated/project/$projectId_/activity/$activityId/resources': typeof AuthenticatedProjectProjectIdActivityActivityIdResourcesRoute
  '/_authenticated/project/$projectId_/activity/$activityId/seating': typeof AuthenticatedProjectProjectIdActivityActivityIdSeatingRoute
  '/_authenticated/project/$projectId_/activity/$activityId/venue': typeof AuthenticatedProjectProjectIdActivityActivityIdVenueRoute
  '/_authenticated/project/$projectId_/activity/$activityId/': typeof AuthenticatedProjectProjectIdActivityActivityIdIndexRoute
  '/_authenticated/project/$projectId_/activity/$activityId/invitations/generate': typeof AuthenticatedProjectProjectIdActivityActivityIdInvitationsGenerateRoute
  '/_authenticated/project/$projectId_/activity/$activityId/agenda/': typeof AuthenticatedProjectProjectIdActivityActivityIdAgendaIndexRoute
  '/_authenticated/project/$projectId_/activity/$activityId/invitations/': typeof AuthenticatedProjectProjectIdActivityActivityIdInvitationsIndexRoute
  '/_authenticated/project/$projectId_/activity/$activityId/resource-ledger/': typeof AuthenticatedProjectProjectIdActivityActivityIdResourceLedgerIndexRoute
  '/_authenticated/project/$projectId_/activity/$activityId/trip/': typeof AuthenticatedProjectProjectIdActivityActivityIdTripIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$'
    | '/dashboard'
    | '/project/$projectId'
    | '/project/list'
    | '/system/role'
    | '/system/user'
    | '/member/'
    | '/supplier/'
    | '/project/$projectId/members'
    | '/supplier/$supplierId/quote'
    | '/invitation/template/'
    | '/project/$projectId/'
    | '/project/$projectId/activity/$activityId'
    | '/project/$projectId/activity/$activityId/config'
    | '/project/$projectId/activity/$activityId/members'
    | '/project/$projectId/activity/$activityId/registration'
    | '/project/$projectId/activity/$activityId/resources'
    | '/project/$projectId/activity/$activityId/seating'
    | '/project/$projectId/activity/$activityId/venue'
    | '/project/$projectId/activity/$activityId/'
    | '/project/$projectId/activity/$activityId/invitations/generate'
    | '/project/$projectId/activity/$activityId/agenda/'
    | '/project/$projectId/activity/$activityId/invitations/'
    | '/project/$projectId/activity/$activityId/resource-ledger/'
    | '/project/$projectId/activity/$activityId/trip/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/$'
    | '/dashboard'
    | '/project/list'
    | '/system/role'
    | '/system/user'
    | '/member'
    | '/supplier'
    | '/project/$projectId/members'
    | '/supplier/$supplierId/quote'
    | '/invitation/template'
    | '/project/$projectId'
    | '/project/$projectId/activity/$activityId/config'
    | '/project/$projectId/activity/$activityId/members'
    | '/project/$projectId/activity/$activityId/registration'
    | '/project/$projectId/activity/$activityId/resources'
    | '/project/$projectId/activity/$activityId/seating'
    | '/project/$projectId/activity/$activityId/venue'
    | '/project/$projectId/activity/$activityId'
    | '/project/$projectId/activity/$activityId/invitations/generate'
    | '/project/$projectId/activity/$activityId/agenda'
    | '/project/$projectId/activity/$activityId/invitations'
    | '/project/$projectId/activity/$activityId/resource-ledger'
    | '/project/$projectId/activity/$activityId/trip'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/$'
    | '/_authenticated/dashboard'
    | '/_authenticated/project/$projectId'
    | '/_authenticated/project/list'
    | '/_authenticated/system/role'
    | '/_authenticated/system/user'
    | '/_authenticated/member/'
    | '/_authenticated/supplier/'
    | '/_authenticated/project/$projectId/members'
    | '/_authenticated/supplier/$supplierId/quote'
    | '/_authenticated/invitation/template/'
    | '/_authenticated/project/$projectId/'
    | '/_authenticated/project/$projectId_/activity/$activityId'
    | '/_authenticated/project/$projectId_/activity/$activityId/config'
    | '/_authenticated/project/$projectId_/activity/$activityId/members'
    | '/_authenticated/project/$projectId_/activity/$activityId/registration'
    | '/_authenticated/project/$projectId_/activity/$activityId/resources'
    | '/_authenticated/project/$projectId_/activity/$activityId/seating'
    | '/_authenticated/project/$projectId_/activity/$activityId/venue'
    | '/_authenticated/project/$projectId_/activity/$activityId/'
    | '/_authenticated/project/$projectId_/activity/$activityId/invitations/generate'
    | '/_authenticated/project/$projectId_/activity/$activityId/agenda/'
    | '/_authenticated/project/$projectId_/activity/$activityId/invitations/'
    | '/_authenticated/project/$projectId_/activity/$activityId/resource-ledger/'
    | '/_authenticated/project/$projectId_/activity/$activityId/trip/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/$': {
      id: '/_authenticated/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AuthenticatedSplatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/member/': {
      id: '/_authenticated/member/'
      path: '/member'
      fullPath: '/member/'
      preLoaderRoute: typeof AuthenticatedMemberIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/project/$projectId': {
      id: '/_authenticated/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectProjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/project/list': {
      id: '/_authenticated/project/list'
      path: '/project/list'
      fullPath: '/project/list'
      preLoaderRoute: typeof AuthenticatedProjectListRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/supplier/': {
      id: '/_authenticated/supplier/'
      path: '/supplier'
      fullPath: '/supplier/'
      preLoaderRoute: typeof AuthenticatedSupplierIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/system/role': {
      id: '/_authenticated/system/role'
      path: '/system/role'
      fullPath: '/system/role'
      preLoaderRoute: typeof AuthenticatedSystemRoleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/system/user': {
      id: '/_authenticated/system/user'
      path: '/system/user'
      fullPath: '/system/user'
      preLoaderRoute: typeof AuthenticatedSystemUserRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invitation/template/': {
      id: '/_authenticated/invitation/template/'
      path: '/invitation/template'
      fullPath: '/invitation/template/'
      preLoaderRoute: typeof AuthenticatedInvitationTemplateIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/project/$projectId/': {
      id: '/_authenticated/project/$projectId/'
      path: '/'
      fullPath: '/project/$projectId/'
      preLoaderRoute: typeof AuthenticatedProjectProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedProjectProjectIdRoute
    }
    '/_authenticated/project/$projectId/members': {
      id: '/_authenticated/project/$projectId/members'
      path: '/members'
      fullPath: '/project/$projectId/members'
      preLoaderRoute: typeof AuthenticatedProjectProjectIdMembersRouteImport
      parentRoute: typeof AuthenticatedProjectProjectIdRoute
    }
    '/_authenticated/supplier/$supplierId/quote': {
      id: '/_authenticated/supplier/$supplierId/quote'
      path: '/supplier/$supplierId/quote'
      fullPath: '/supplier/$supplierId/quote'
      preLoaderRoute: typeof AuthenticatedSupplierSupplierIdQuoteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/project/$projectId_/activity/$activityId': {
      id: '/_authenticated/project/$projectId_/activity/$activityId'
      path: '/project/$projectId/activity/$activityId'
      fullPath: '/project/$projectId/activity/$activityId'
      preLoaderRoute: typeof AuthenticatedProjectProjectIdActivityActivityIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/project/$projectId_/activity/$activityId/': {
      id: '/_authenticated/project/$projectId_/activity/$activityId/'
      path: '/'
      fullPath: '/project/$projectId/activity/$activityId/'
      preLoaderRoute: typeof AuthenticatedProjectProjectIdActivityActivityIdIndexRouteImport
      parentRoute: typeof AuthenticatedProjectProjectIdActivityActivityIdRoute
    }
    '/_authenticated/project/$projectId_/activity/$activityId/config': {
      id: '/_authenticated/project/$projectId_/activity/$activityId/config'
      path: '/config'
      fullPath: '/project/$projectId/activity/$activityId/config'
      preLoaderRoute: typeof AuthenticatedProjectProjectIdActivityActivityIdConfigRouteImport
      parentRoute: typeof AuthenticatedProjectProjectIdActivityActivityIdRoute
    }
    '/_authenticated/project/$projectId_/activity/$activityId/members': {
      id: '/_authenticated/project/$projectId_/activity/$activityId/members'
      path: '/members'
      fullPath: '/project/$projectId/activity/$activityId/members'
      preLoaderRoute: typeof AuthenticatedProjectProjectIdActivityActivityIdMembersRouteImport
      parentRoute: typeof AuthenticatedProjectProjectIdActivityActivityIdRoute
    }
    '/_authenticated/project/$projectId_/activity/$activityId/registration': {
      id: '/_authenticated/project/$projectId_/activity/$activityId/registration'
      path: '/registration'
      fullPath: '/project/$projectId/activity/$activityId/registration'
      preLoaderRoute: typeof AuthenticatedProjectProjectIdActivityActivityIdRegistrationRouteImport
      parentRoute: typeof AuthenticatedProjectProjectIdActivityActivityIdRoute
    }
    '/_authenticated/project/$projectId_/activity/$activityId/resources': {
      id: '/_authenticated/project/$projectId_/activity/$activityId/resources'
      path: '/resources'
      fullPath: '/project/$projectId/activity/$activityId/resources'
      preLoaderRoute: typeof AuthenticatedProjectProjectIdActivityActivityIdResourcesRouteImport
      parentRoute: typeof AuthenticatedProjectProjectIdActivityActivityIdRoute
    }
    '/_authenticated/project/$projectId_/activity/$activityId/seating': {
      id: '/_authenticated/project/$projectId_/activity/$activityId/seating'
      path: '/seating'
      fullPath: '/project/$projectId/activity/$activityId/seating'
      preLoaderRoute: typeof AuthenticatedProjectProjectIdActivityActivityIdSeatingRouteImport
      parentRoute: typeof AuthenticatedProjectProjectIdActivityActivityIdRoute
    }
    '/_authenticated/project/$projectId_/activity/$activityId/venue': {
      id: '/_authenticated/project/$projectId_/activity/$activityId/venue'
      path: '/venue'
      fullPath: '/project/$projectId/activity/$activityId/venue'
      preLoaderRoute: typeof AuthenticatedProjectProjectIdActivityActivityIdVenueRouteImport
      parentRoute: typeof AuthenticatedProjectProjectIdActivityActivityIdRoute
    }
    '/_authenticated/project/$projectId_/activity/$activityId/agenda/': {
      id: '/_authenticated/project/$projectId_/activity/$activityId/agenda/'
      path: '/agenda'
      fullPath: '/project/$projectId/activity/$activityId/agenda/'
      preLoaderRoute: typeof AuthenticatedProjectProjectIdActivityActivityIdAgendaIndexRouteImport
      parentRoute: typeof AuthenticatedProjectProjectIdActivityActivityIdRoute
    }
    '/_authenticated/project/$projectId_/activity/$activityId/invitations/': {
      id: '/_authenticated/project/$projectId_/activity/$activityId/invitations/'
      path: '/invitations'
      fullPath: '/project/$projectId/activity/$activityId/invitations/'
      preLoaderRoute: typeof AuthenticatedProjectProjectIdActivityActivityIdInvitationsIndexRouteImport
      parentRoute: typeof AuthenticatedProjectProjectIdActivityActivityIdRoute
    }
    '/_authenticated/project/$projectId_/activity/$activityId/invitations/generate': {
      id: '/_authenticated/project/$projectId_/activity/$activityId/invitations/generate'
      path: '/invitations/generate'
      fullPath: '/project/$projectId/activity/$activityId/invitations/generate'
      preLoaderRoute: typeof AuthenticatedProjectProjectIdActivityActivityIdInvitationsGenerateRouteImport
      parentRoute: typeof AuthenticatedProjectProjectIdActivityActivityIdRoute
    }
    '/_authenticated/project/$projectId_/activity/$activityId/resource-ledger/': {
      id: '/_authenticated/project/$projectId_/activity/$activityId/resource-ledger/'
      path: '/resource-ledger'
      fullPath: '/project/$projectId/activity/$activityId/resource-ledger/'
      preLoaderRoute: typeof AuthenticatedProjectProjectIdActivityActivityIdResourceLedgerIndexRouteImport
      parentRoute: typeof AuthenticatedProjectProjectIdActivityActivityIdRoute
    }
    '/_authenticated/project/$projectId_/activity/$activityId/trip/': {
      id: '/_authenticated/project/$projectId_/activity/$activityId/trip/'
      path: '/trip'
      fullPath: '/project/$projectId/activity/$activityId/trip/'
      preLoaderRoute: typeof AuthenticatedProjectProjectIdActivityActivityIdTripIndexRouteImport
      parentRoute: typeof AuthenticatedProjectProjectIdActivityActivityIdRoute
    }
  }
}

interface AuthenticatedProjectProjectIdRouteChildren {
  AuthenticatedProjectProjectIdMembersRoute: typeof AuthenticatedProjectProjectIdMembersRoute
  AuthenticatedProjectProjectIdIndexRoute: typeof AuthenticatedProjectProjectIdIndexRoute
}

const AuthenticatedProjectProjectIdRouteChildren: AuthenticatedProjectProjectIdRouteChildren =
  {
    AuthenticatedProjectProjectIdMembersRoute:
      AuthenticatedProjectProjectIdMembersRoute,
    AuthenticatedProjectProjectIdIndexRoute:
      AuthenticatedProjectProjectIdIndexRoute,
  }

const AuthenticatedProjectProjectIdRouteWithChildren =
  AuthenticatedProjectProjectIdRoute._addFileChildren(
    AuthenticatedProjectProjectIdRouteChildren,
  )

interface AuthenticatedProjectProjectIdActivityActivityIdRouteChildren {
  AuthenticatedProjectProjectIdActivityActivityIdConfigRoute: typeof AuthenticatedProjectProjectIdActivityActivityIdConfigRoute
  AuthenticatedProjectProjectIdActivityActivityIdMembersRoute: typeof AuthenticatedProjectProjectIdActivityActivityIdMembersRoute
  AuthenticatedProjectProjectIdActivityActivityIdRegistrationRoute: typeof AuthenticatedProjectProjectIdActivityActivityIdRegistrationRoute
  AuthenticatedProjectProjectIdActivityActivityIdResourcesRoute: typeof AuthenticatedProjectProjectIdActivityActivityIdResourcesRoute
  AuthenticatedProjectProjectIdActivityActivityIdSeatingRoute: typeof AuthenticatedProjectProjectIdActivityActivityIdSeatingRoute
  AuthenticatedProjectProjectIdActivityActivityIdVenueRoute: typeof AuthenticatedProjectProjectIdActivityActivityIdVenueRoute
  AuthenticatedProjectProjectIdActivityActivityIdIndexRoute: typeof AuthenticatedProjectProjectIdActivityActivityIdIndexRoute
  AuthenticatedProjectProjectIdActivityActivityIdInvitationsGenerateRoute: typeof AuthenticatedProjectProjectIdActivityActivityIdInvitationsGenerateRoute
  AuthenticatedProjectProjectIdActivityActivityIdAgendaIndexRoute: typeof AuthenticatedProjectProjectIdActivityActivityIdAgendaIndexRoute
  AuthenticatedProjectProjectIdActivityActivityIdInvitationsIndexRoute: typeof AuthenticatedProjectProjectIdActivityActivityIdInvitationsIndexRoute
  AuthenticatedProjectProjectIdActivityActivityIdResourceLedgerIndexRoute: typeof AuthenticatedProjectProjectIdActivityActivityIdResourceLedgerIndexRoute
  AuthenticatedProjectProjectIdActivityActivityIdTripIndexRoute: typeof AuthenticatedProjectProjectIdActivityActivityIdTripIndexRoute
}

const AuthenticatedProjectProjectIdActivityActivityIdRouteChildren: AuthenticatedProjectProjectIdActivityActivityIdRouteChildren =
  {
    AuthenticatedProjectProjectIdActivityActivityIdConfigRoute:
      AuthenticatedProjectProjectIdActivityActivityIdConfigRoute,
    AuthenticatedProjectProjectIdActivityActivityIdMembersRoute:
      AuthenticatedProjectProjectIdActivityActivityIdMembersRoute,
    AuthenticatedProjectProjectIdActivityActivityIdRegistrationRoute:
      AuthenticatedProjectProjectIdActivityActivityIdRegistrationRoute,
    AuthenticatedProjectProjectIdActivityActivityIdResourcesRoute:
      AuthenticatedProjectProjectIdActivityActivityIdResourcesRoute,
    AuthenticatedProjectProjectIdActivityActivityIdSeatingRoute:
      AuthenticatedProjectProjectIdActivityActivityIdSeatingRoute,
    AuthenticatedProjectProjectIdActivityActivityIdVenueRoute:
      AuthenticatedProjectProjectIdActivityActivityIdVenueRoute,
    AuthenticatedProjectProjectIdActivityActivityIdIndexRoute:
      AuthenticatedProjectProjectIdActivityActivityIdIndexRoute,
    AuthenticatedProjectProjectIdActivityActivityIdInvitationsGenerateRoute:
      AuthenticatedProjectProjectIdActivityActivityIdInvitationsGenerateRoute,
    AuthenticatedProjectProjectIdActivityActivityIdAgendaIndexRoute:
      AuthenticatedProjectProjectIdActivityActivityIdAgendaIndexRoute,
    AuthenticatedProjectProjectIdActivityActivityIdInvitationsIndexRoute:
      AuthenticatedProjectProjectIdActivityActivityIdInvitationsIndexRoute,
    AuthenticatedProjectProjectIdActivityActivityIdResourceLedgerIndexRoute:
      AuthenticatedProjectProjectIdActivityActivityIdResourceLedgerIndexRoute,
    AuthenticatedProjectProjectIdActivityActivityIdTripIndexRoute:
      AuthenticatedProjectProjectIdActivityActivityIdTripIndexRoute,
  }

const AuthenticatedProjectProjectIdActivityActivityIdRouteWithChildren =
  AuthenticatedProjectProjectIdActivityActivityIdRoute._addFileChildren(
    AuthenticatedProjectProjectIdActivityActivityIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedSplatRoute: typeof AuthenticatedSplatRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProjectProjectIdRoute: typeof AuthenticatedProjectProjectIdRouteWithChildren
  AuthenticatedProjectListRoute: typeof AuthenticatedProjectListRoute
  AuthenticatedSystemRoleRoute: typeof AuthenticatedSystemRoleRoute
  AuthenticatedSystemUserRoute: typeof AuthenticatedSystemUserRoute
  AuthenticatedMemberIndexRoute: typeof AuthenticatedMemberIndexRoute
  AuthenticatedSupplierIndexRoute: typeof AuthenticatedSupplierIndexRoute
  AuthenticatedSupplierSupplierIdQuoteRoute: typeof AuthenticatedSupplierSupplierIdQuoteRoute
  AuthenticatedInvitationTemplateIndexRoute: typeof AuthenticatedInvitationTemplateIndexRoute
  AuthenticatedProjectProjectIdActivityActivityIdRoute: typeof AuthenticatedProjectProjectIdActivityActivityIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSplatRoute: AuthenticatedSplatRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProjectProjectIdRoute:
    AuthenticatedProjectProjectIdRouteWithChildren,
  AuthenticatedProjectListRoute: AuthenticatedProjectListRoute,
  AuthenticatedSystemRoleRoute: AuthenticatedSystemRoleRoute,
  AuthenticatedSystemUserRoute: AuthenticatedSystemUserRoute,
  AuthenticatedMemberIndexRoute: AuthenticatedMemberIndexRoute,
  AuthenticatedSupplierIndexRoute: AuthenticatedSupplierIndexRoute,
  AuthenticatedSupplierSupplierIdQuoteRoute:
    AuthenticatedSupplierSupplierIdQuoteRoute,
  AuthenticatedInvitationTemplateIndexRoute:
    AuthenticatedInvitationTemplateIndexRoute,
  AuthenticatedProjectProjectIdActivityActivityIdRoute:
    AuthenticatedProjectProjectIdActivityActivityIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
