import { pathToFileURL } from "node:url";
import { pushSchema } from "drizzle-kit/api";
import { sql } from "drizzle-orm";
import { db } from "../infra/db";
import type { SeedContext, SeedFn } from "./context";

// 把一个**空库**准备成可用的开发库：建表 → 依次跑种子 → 重置序列。
// 由 scripts/dev.ts 以子进程方式调用，DATABASE_URL 由父进程注入。
//
// 只对空库负责：`bun run dev` 每次都起全新的 tmpfs 容器（见 scripts/dev-db.ts），
// 所以种子不需要幂等，也不需要任何 onConflict / 先查再插的噪音。

/**
 * 先确认自己连的确实是父进程指定的那个库，再动手建表。
 *
 * DATABASE_URL 的注入依赖「进程环境变量压过 --env-file」这条 bun 行为。这条
 * 行为一旦变化，失败方式会是**悄悄连到持久库并对它 push schema**（push 会为了
 * 对齐而删列改类型）—— 属于绝不能静默发生的那一类。所以父进程额外传一份
 * EXPECTED_DATABASE_URL，这里两头都核：环境变量本身，以及真正连上之后
 * 数据库自己报的名字。
 */
async function assertConnectedToExpectedDatabase() {
  const expected = process.env.EXPECTED_DATABASE_URL?.trim();

  // 没传就是有人手动跑这个脚本，不强制。
  if (!expected) {
    return;
  }

  const actual = process.env.DATABASE_URL?.trim();
  if (actual !== expected) {
    throw new Error(
      `DATABASE_URL 没有按预期注入。期望 ${expected}，实际 ${actual ?? "(未设置)"}。` +
        "多半是 bun 的 --env-file 优先级变了，停下来别对错误的库建表。",
    );
  }

  const expectedName = new URL(expected).pathname.replace(/^\//, "");
  const result = await db.execute<{ name: string }>(
    sql`select current_database() as name`,
  );
  const actualName = result.rows[0]?.name;

  if (actualName !== expectedName) {
    throw new Error(
      `连上的数据库是 "${actualName}"，但期望是 "${expectedName}"，拒绝继续。`,
    );
  }
}

async function buildSchema() {
  // Glob 而不是一个个手写 import：新增 modules/<名>/schema.ts 不用动这里，
  // 和 drizzle.config.ts 里 schema 那条 glob 是同一个理由。
  const glob = new Bun.Glob("*/schema.ts");
  const modulesDir = new URL("../modules/", import.meta.url);
  const schema: Record<string, unknown> = {};

  for await (const relativePath of glob.scan({
    cwd: Bun.fileURLToPath(modulesDir),
  })) {
    const moduleUrl = new URL(relativePath.replaceAll("\\", "/"), modulesDir);
    for (const [name, value] of Object.entries(await import(moduleUrl.href))) {
      schema[name] = value;
    }
  }

  return schema;
}

async function pushTables() {
  const schema = await buildSchema();
  // drizzle-kit/api 的入参类型比这里能构造的对象窄一档（它想要 kit 内部那份
  // schema 表示）。**必须走 API 不能 spawn CLI**：`drizzle-kit push` 的 CLI
  // 在非交互环境下会卡住然后 exit 1，且不打印任何原因。
  const { apply, statementsToExecute } = await pushSchema(
    schema as never,
    db as never,
  );
  await apply();

  return statementsToExecute.length;
}

/**
 * 种子写死了 ID（见 context.ts 的 DEMO），而 `generated by default as identity`
 * 的序列不会因为显式插入而前进 —— 不推一把的话，从界面新增的第一条记录就会
 * 撞主键。这里一次性把 public 下所有 identity 列的序列推到 max(id)。
 */
async function resyncIdentitySequences() {
  await db.execute(sql`
    do $$
    declare
      target record;
      max_id bigint;
    begin
      for target in
        select c.table_name, c.column_name,
               pg_get_serial_sequence(
                 format('%I.%I', c.table_schema, c.table_name), c.column_name
               ) as seq
        from information_schema.columns c
        where c.table_schema = 'public' and c.is_identity = 'YES'
      loop
        if target.seq is not null then
          execute format('select coalesce(max(%I), 0) from %I',
                         target.column_name, target.table_name)
            into max_id;
          perform setval(target.seq, greatest(max_id, 1), max_id > 0);
        end if;
      end loop;
    end $$;
  `);
}

// 执行顺序 = 文件名顺序，外键依赖靠数字前缀表达。两位数字是强制的：
// 文件名排序是字典序不是数值序，混进 `5-` 或 `100-` 会让顺序变得和肉眼
// 读到的不一样，而症状是一条外键报错，不会指向命名。
const SEED_FILE_PATTERN = /^(\d{2})-[a-z0-9-]+\.ts$/;

async function listSeedFiles() {
  const glob = new Bun.Glob("*.ts");
  const files = (await Array.fromAsync(glob.scan({ cwd: import.meta.dir })))
    .map((name) => name.replaceAll("\\", "/"))
    .filter((name) => /^\d/.test(name))
    .sort();

  const seenPrefixes = new Map<string, string>();

  for (const file of files) {
    const matched = SEED_FILE_PATTERN.exec(file);

    if (!matched) {
      throw new Error(
        `种子文件名不合规：dev-seed/${file}。必须是「两位数字 + 短横线 + 小写名」，例如 20-project.ts。`,
      );
    }

    const prefix = matched[1] as string;
    const previous = seenPrefixes.get(prefix);
    if (previous) {
      throw new Error(
        `种子序号重复：dev-seed/${previous} 和 dev-seed/${file} 都是 ${prefix}-。` +
          "序号决定执行顺序，重复时顺序取决于文件名的其余部分，不可靠——改一个即可（序号留了间隔）。",
      );
    }
    seenPrefixes.set(prefix, file);
  }

  return files;
}

async function runSeeds() {
  const files = await listSeedFiles();
  const context: SeedContext = { userId: "" };

  for (const file of files) {
    const moduleUrl = pathToFileURL(`${import.meta.dir}/${file}`).href;
    const loaded = (await import(moduleUrl)) as { seed?: SeedFn };

    if (typeof loaded.seed !== "function") {
      throw new Error(`dev-seed/${file} 没有导出 seed 函数`);
    }

    try {
      await loaded.seed(db, context);
    } catch (error) {
      // 指名道姓地报是哪个文件炸的。种子失败会让 dev 整体启动失败（见
      // scripts/dev.ts）—— 在灌了一半的库上调试得出的结论全是错的，
      // 比启动失败难查十倍。
      throw new Error(`dev-seed/${file} 执行失败：${(error as Error).message}`, {
        cause: error,
      });
    }
  }

  return files;
}

const startedAt = Date.now();
await assertConnectedToExpectedDatabase();
const statementCount = await pushTables();
const seededFiles = await runSeeds();
await resyncIdentitySequences();

console.log(
  `[dev] 数据库就位：${statementCount} 条建表语句，${seededFiles.length} 个种子文件（${Date.now() - startedAt}ms）`,
);

process.exit(0);
