import {
  existsSync,
  lstatSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { dirname, resolve } from "node:path";
import { YAML } from "bun";
import { checkLocalLinks } from "./docs-list";

const marker =
  "<!-- generated by bun run skills:sync; edit .agents/skills instead -->";
const normalize = (text: string) => text.replace(/\r\n/g, "\n");

function skillDirectories(root: string, directory: string) {
  const absolute = resolve(root, directory);
  if (!existsSync(absolute)) return [];
  if (lstatSync(absolute).isSymbolicLink())
    throw new Error(`${directory}: 受管理的 skill 目录不能是链接`);
  return readdirSync(absolute, { withFileTypes: true })
    .filter((entry) => !entry.name.startsWith("."))
    .map((entry) => {
      if (entry.isSymbolicLink())
        throw new Error(
          `${directory}/${entry.name}: 受管理的 skill 不能是链接`,
        );
      return entry;
    })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();
}

function adapter(root: string, name: string) {
  const path = `.agents/skills/${name}/SKILL.md`;
  const text = normalize(readFileSync(resolve(root, path), "utf8"));
  const header = /^---\n([\s\S]*?)\n---\n/.exec(text);
  if (!header) throw new Error(`${path}: 缺少 YAML frontmatter`);
  const data = YAML.parse(header[1]) as Record<string, unknown> | null;
  if (
    !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(name) ||
    name.length > 64 ||
    data?.name !== name ||
    typeof data.description !== "string" ||
    !data.description.trim() ||
    data.description.length > 1024
  )
    throw new Error(
      `${path}: name 必须匹配目录，description 必须为非空简短文本`,
    );
  const metadata = data.metadata as Record<string, unknown> | undefined;
  const invocable = metadata?.["claude-user-invocable"];
  if (invocable !== undefined && invocable !== "true" && invocable !== "false")
    throw new Error(
      `${path}: claude-user-invocable 必须是字符串 true 或 false`,
    );
  // 不透传权限、动态命令或任意宿主配置；新增宿主语义需单独审阅。
  const unsupported = Object.keys(data).filter(
    (key) => !["name", "description", "metadata", "license"].includes(key),
  );
  if (unsupported.length)
    throw new Error(`${path}: 未适配的宿主字段 ${unsupported.join(", ")}`);
  return {
    path,
    text,
    content: `---\nname: ${name}\ndescription: ${JSON.stringify(data.description)}\n${invocable === undefined ? "" : `user-invocable: ${invocable}\n`}---\n\n${marker}\n\n先读取并遵循 [项目 skill 正文](../../../.agents/skills/${name}/SKILL.md)，再执行当前任务。正文及其参考资料的相对路径以原文件所在目录为基准；不要只凭本入口的摘要操作。\n`,
  };
}

export function inspectSkills(root: string) {
  const errors: string[] = [];
  const pending: { path: string; content: string }[] = [];
  const names = skillDirectories(root, ".agents/skills");
  const targets = skillDirectories(root, ".claude/skills");
  if (!names.length) errors.push(".agents/skills: 未发现项目 skill");
  for (const name of names) {
    try {
      const source = adapter(root, name);
      errors.push(...checkLocalLinks(root, source.path, source.text));
      const path = `.claude/skills/${name}/SKILL.md`;
      const absolute = resolve(root, path);
      if (existsSync(absolute) && lstatSync(absolute).isSymbolicLink()) {
        errors.push(`${path}: 不能写入链接`);
        continue;
      }
      const current = existsSync(absolute)
        ? normalize(readFileSync(absolute, "utf8"))
        : null;
      if (current !== null && !current.includes(marker)) {
        errors.push(`${path}: 已有非生成入口，先审阅归属，不能自动覆盖`);
        continue;
      }
      if (current !== source.content)
        pending.push({ path, content: source.content });
    } catch (error) {
      errors.push(error instanceof Error ? error.message : String(error));
    }
  }
  for (const name of targets.filter((name) => !names.includes(name))) {
    const path = `.claude/skills/${name}/SKILL.md`;
    if (
      existsSync(resolve(root, path)) &&
      readFileSync(resolve(root, path), "utf8").includes(marker)
    )
      errors.push(`${path}: 源 skill 已移除；审阅后删除过期入口`);
  }
  return { errors, pending, count: names.length };
}

export function syncSkills(root: string) {
  const result = inspectSkills(root);
  if (result.errors.length) throw new Error(result.errors.join("\n"));
  for (const item of result.pending) {
    const absolute = resolve(root, item.path);
    mkdirSync(dirname(absolute), { recursive: true });
    writeFileSync(absolute, item.content);
  }
  return result.pending.length;
}

if (import.meta.main) {
  const args = process.argv.slice(2);
  const root = resolve(import.meta.dir, "..");
  try {
    if (args.length !== 1 || !["--check", "--sync"].includes(args[0]))
      throw new Error("用法：bun scripts/skills.ts --check | --sync");
    if (args[0] === "--sync") {
      console.log(`已同步 ${syncSkills(root)} 个 Claude Code 薄入口`);
    } else {
      const result = inspectSkills(root);
      const errors = [
        ...result.errors,
        ...result.pending.map(
          (item) => `${item.path}: 缺失或漂移，运行 bun run skills:sync`,
        ),
      ];
      if (errors.length) throw new Error(errors.join("\n"));
      console.log(
        `${result.count} 个项目 skill 的元数据、正文链接和 Claude Code 入口检查通过`,
      );
    }
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  }
}
